### ISSUE TITLE
not working with my setup on glucolog web v1.7.3

### ISSUE THREAD

**Issue by mcurly** [yaronkhazai/gmns-bridge#2]
Hello,

Before anything else, thankyou for your willingness in trying to connect something that up until now doesn't seem possible.

Can you assure that this app of yours works with latest glucolog web v1.7.3?

Thank you.

Hope to hear from you soon!

**Comment by yaronkhazai** [comment]
Hi

yes, it is working on v1.7.3

what is the problem you have?
How & where (local/aws/azure/..) are you trying to run it ?
can you send me some of the logs or error?

**Comment by mcurly** [comment]
Hi again, thank you for your answer.

I am trying to run it from AWS.

I believe I am doing the correct steps to set it up, although I am not 100% sure, I used Google translator to get a gist of your Bulgarian instructions.


Also I am new to AWS and even can not trace or provide logs that would be so helpful and decisive in determining what may be the issue with my configuration.

What indeed is happening is there isn't any syncing between glucologweb and nightscout. And, I repeat, I don't even know if the AWS lambda function together with AWS trigger is working or not.

In the config.yaml file, I am not sure if I have filled the required parameters correctly. I know that yaml is very picky on its syntax, and its parametrization has strict rules. For instance, extra spaces or tab spaces are known to mess up the intended configs. The same goes for special characters like the dash "-" or the forward slash "/” that one finds in URL addresses, or other special characters, that may be present in the password variables.

May I suggest that you share an example config.yaml file, already filled up, with "fony" information, but still admissable (for instance instead of "<string variables>" put an actual example:

```
glucologweb:
  username: <glucologweb username/email>
  password: <glucologweb Password>
  timeZoneOffset: UTC
  loginURL: https://www.glucologweb.com/login-tz
  dataURL: https://www.glucologweb.com/cgm/getDayGraphData/
  units: mmol/l #mg/dl

nightscout:
  URL: <nightScout URL>
  token: <nightScout Token>
```


Might be (for instance, this is just a suggestion):

```
glucologweb:
  username: john.doe@acme.com     #don't email addresses need to be escaped somehow?
  password: @#$@$354!?&     #and the ackward password characters, escaped as well?
  timeZoneOffset: UTC
  loginURL: https://www.glucologweb.com/login-tz
  dataURL: https://www.glucologweb.com/cgm/getDayGraphData/
  units: mmol/l #mg/dl

nightscout:
  URL:      #nighscout address example
  token:    #nightscout token example
```

Thank you again and sorry for this long post.

I will try shortly to run the local python/yaml solution that you've posted today and post its results in a while.


Cheers.
